version: "3"
services:
  web:
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongodb
    env_file:
      - .env.docker.local
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: "none"
